// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.c3d2.matemat.web.converter;

import de.c3d2.matemat.web.converter.DrinkConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DrinkConverter_Roo_Configurable {
    
    declare @type: DrinkConverter: @Configurable;
    
}
