// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.c3d2.matemat.web;

import de.c3d2.matemat.web.BottleBean;
import java.io.Serializable;

privileged aspect BottleBean_Roo_Serializable {
    
    declare parents: BottleBean implements Serializable;
    
    private static final long BottleBean.serialVersionUID = 1L;
    
}
