// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.c3d2.matemat.web;

import de.c3d2.matemat.web.DrinkBean;
import java.io.Serializable;

privileged aspect DrinkBean_Roo_Serializable {
    
    declare parents: DrinkBean implements Serializable;
    
    private static final long DrinkBean.serialVersionUID = 1L;
    
}
