// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.c3d2.matemat.web;

import de.c3d2.matemat.web.DrinkBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DrinkBean_Roo_Configurable {
    
    declare @type: DrinkBean: @Configurable;
    
}
