// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.c3d2.matemat.web;

import de.c3d2.matemat.web.HackerBean;
import java.io.Serializable;

privileged aspect HackerBean_Roo_Serializable {
    
    declare parents: HackerBean implements Serializable;
    
    private static final long HackerBean.serialVersionUID = 1L;
    
}
