// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.c3d2.matemat.web;

import de.c3d2.matemat.web.KasseBean;
import java.io.Serializable;

privileged aspect KasseBean_Roo_Serializable {
    
    declare parents: KasseBean implements Serializable;
    
    private static final long KasseBean.serialVersionUID = 1L;
    
}
