// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.c3d2.matemat.web;

import de.c3d2.matemat.web.TransactionBean;
import java.io.Serializable;

privileged aspect TransactionBean_Roo_Serializable {
    
    declare parents: TransactionBean implements Serializable;
    
    private static final long TransactionBean.serialVersionUID = 1L;
    
}
