// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.c3d2.matemat.domain;

import de.c3d2.matemat.domain.Hacker;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Hacker_Roo_Jpa_Entity {
    
    declare @type: Hacker: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Hacker.id;
    
    @Version
    @Column(name = "version")
    private Integer Hacker.version;
    
    public Hacker.new() {
        super();
    }

    public Long Hacker.getId() {
        return this.id;
    }
    
    public void Hacker.setId(Long id) {
        this.id = id;
    }
    
    public Integer Hacker.getVersion() {
        return this.version;
    }
    
    public void Hacker.setVersion(Integer version) {
        this.version = version;
    }
    
}
