// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.c3d2.matemat.domain;

import de.c3d2.matemat.domain.Hacker;
import java.util.Date;

privileged aspect Hacker_Roo_JavaBean {
    
    public String Hacker.getName() {
        return this.name;
    }
    
    public void Hacker.setName(String name) {
        this.name = name;
    }
    
    public Float Hacker.getAmount() {
        return this.amount;
    }
    
    public void Hacker.setAmount(Float amount) {
        this.amount = amount;
    }
    
    public String Hacker.getPin() {
        return this.pin;
    }
    
    public void Hacker.setPin(String pin) {
        this.pin = pin;
    }
    
    public Date Hacker.getLastDrink() {
        return this.lastDrink;
    }
    
    public void Hacker.setLastDrink(Date lastDrink) {
        this.lastDrink = lastDrink;
    }
    
}
