// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.c3d2.matemat.domain;

import de.c3d2.matemat.domain.Kasse;

privileged aspect Kasse_Roo_JavaBean {
    
    public Float Kasse.getAmount() {
        return this.amount;
    }
    
    public void Kasse.setAmount(Float amount) {
        this.amount = amount;
    }
    
}
