// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.c3d2.matemat.domain;

import de.c3d2.matemat.domain.Bottle;
import de.c3d2.matemat.domain.BottleDataOnDemand;
import de.c3d2.matemat.domain.Drink;
import de.c3d2.matemat.domain.DrinkDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect BottleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BottleDataOnDemand: @Component;
    
    private Random BottleDataOnDemand.rnd = new SecureRandom();
    
    private List<Bottle> BottleDataOnDemand.data;
    
    @Autowired
    DrinkDataOnDemand BottleDataOnDemand.drinkDataOnDemand;
    
    public Bottle BottleDataOnDemand.getNewTransientBottle(int index) {
        Bottle obj = new Bottle();
        setDrink(obj, index);
        setFilled(obj, index);
        return obj;
    }
    
    public void BottleDataOnDemand.setDrink(Bottle obj, int index) {
        Drink drink = drinkDataOnDemand.getRandomDrink();
        obj.setDrink(drink);
    }
    
    public void BottleDataOnDemand.setFilled(Bottle obj, int index) {
        Boolean filled = Boolean.TRUE;
        obj.setFilled(filled);
    }
    
    public Bottle BottleDataOnDemand.getSpecificBottle(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Bottle obj = data.get(index);
        Long id = obj.getId();
        return Bottle.findBottle(id);
    }
    
    public Bottle BottleDataOnDemand.getRandomBottle() {
        init();
        Bottle obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Bottle.findBottle(id);
    }
    
    public boolean BottleDataOnDemand.modifyBottle(Bottle obj) {
        return false;
    }
    
    public void BottleDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Bottle.findBottleEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Bottle' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Bottle>();
        for (int i = 0; i < 10; i++) {
            Bottle obj = getNewTransientBottle(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
