// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.c3d2.matemat.domain;

import de.c3d2.matemat.domain.Drink;
import de.c3d2.matemat.domain.DrinkDataOnDemand;
import de.c3d2.matemat.domain.DrinkIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DrinkIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DrinkIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DrinkIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DrinkIntegrationTest: @Transactional;
    
    @Autowired
    DrinkDataOnDemand DrinkIntegrationTest.dod;
    
    @Test
    public void DrinkIntegrationTest.testCountDrinks() {
        Assert.assertNotNull("Data on demand for 'Drink' failed to initialize correctly", dod.getRandomDrink());
        long count = Drink.countDrinks();
        Assert.assertTrue("Counter for 'Drink' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DrinkIntegrationTest.testFindDrink() {
        Drink obj = dod.getRandomDrink();
        Assert.assertNotNull("Data on demand for 'Drink' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Drink' failed to provide an identifier", id);
        obj = Drink.findDrink(id);
        Assert.assertNotNull("Find method for 'Drink' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Drink' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DrinkIntegrationTest.testFindAllDrinks() {
        Assert.assertNotNull("Data on demand for 'Drink' failed to initialize correctly", dod.getRandomDrink());
        long count = Drink.countDrinks();
        Assert.assertTrue("Too expensive to perform a find all test for 'Drink', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Drink> result = Drink.findAllDrinks();
        Assert.assertNotNull("Find all method for 'Drink' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Drink' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DrinkIntegrationTest.testFindDrinkEntries() {
        Assert.assertNotNull("Data on demand for 'Drink' failed to initialize correctly", dod.getRandomDrink());
        long count = Drink.countDrinks();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Drink> result = Drink.findDrinkEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Drink' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Drink' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DrinkIntegrationTest.testFlush() {
        Drink obj = dod.getRandomDrink();
        Assert.assertNotNull("Data on demand for 'Drink' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Drink' failed to provide an identifier", id);
        obj = Drink.findDrink(id);
        Assert.assertNotNull("Find method for 'Drink' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDrink(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Drink' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DrinkIntegrationTest.testMergeUpdate() {
        Drink obj = dod.getRandomDrink();
        Assert.assertNotNull("Data on demand for 'Drink' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Drink' failed to provide an identifier", id);
        obj = Drink.findDrink(id);
        boolean modified =  dod.modifyDrink(obj);
        Integer currentVersion = obj.getVersion();
        Drink merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Drink' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DrinkIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Drink' failed to initialize correctly", dod.getRandomDrink());
        Drink obj = dod.getNewTransientDrink(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Drink' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Drink' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Drink' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DrinkIntegrationTest.testRemove() {
        Drink obj = dod.getRandomDrink();
        Assert.assertNotNull("Data on demand for 'Drink' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Drink' failed to provide an identifier", id);
        obj = Drink.findDrink(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Drink' with identifier '" + id + "'", Drink.findDrink(id));
    }
    
}
